feat: 'list --copy-url' and 'list --browser'

diff --git a/zxz b/zxz
--- a/zxz
+++ b/zxz
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,7 +17,7 @@ version_command() {
 
 # :command.usage
 zxz_usage() {
-  printf "zxz - a CLI to interact with <https://0x0.st/>\n\n"
+  printf "zxz - a CLI to interact with <https://0x0.st/>.\n\n"
 
   printf "%s\n" "Usage:"
   printf "  zxz COMMAND\n"
@@ -26,8 +26,8 @@ zxz_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Upload FILE to https://0x0.st/ (default)\n" "upload"
-  printf "  %s   List the files you already uploaded\n" "list  "
+  printf "  %s   Upload FILE. (default)\n" "upload"
+  printf "  %s   List the files you already uploaded.\n" "list  "
   printf "  %s   Delete an uploaded file from the remote server.\n" "delete"
   echo
 
@@ -43,13 +43,22 @@ zxz_usage() {
     printf "    Show version number\n"
     echo
 
+    # :command.usage_environment_variables
+    printf "%s\n" "Environment Variables:"
+
+    # :environment_variable.usage
+    printf "  %s\n" "ZXZ_LOG_FILE"
+    printf "    Path to the log file.\n"
+    printf "    %s\n" "Default: ${LOG_DIR}/uploads.log"
+    echo
+
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  zxz <filename>\n"
+    printf "  The most simple usage is when you just want to upload a file:\n  $ zxz <filename>\n"
     echo
 
     # :command.footer
-    printf "Credits:\n  zxz repository: https://github.com/meleu/zxz\n\n  The https://0x0.st/ is a service maintained by Mia Herkt,\n  consider supporting them financially (check the webpage).\n\n"
+    printf "Credits:\n  zxz repository: <https://github.com/meleu/zxz>\n\n  The <https://0x0.st/> is a service maintained by Mia Herkt,\n  consider supporting them financially (check the webpage).\n\n"
     echo
 
   fi
@@ -57,7 +66,9 @@ zxz_usage() {
 
 # :command.usage
 zxz_upload_usage() {
-  printf "zxz upload - Upload FILE to https://0x0.st/\n\n"
+  printf "zxz upload - Upload FILE.\n\n"
+  printf "Alias: up, u\n"
+  echo
 
   printf "%s\n" "Usage:"
   printf "  zxz [upload] FILE [OPTIONS]\n"
@@ -71,12 +82,12 @@ zxz_upload_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--secret, -s"
-    printf "    Ask the server to generate a longer and hard-to-guess URL\n"
+    printf "    Ask the server to generate a longer and hard-to-guess URL.\n"
     echo
 
     # :flag.usage
     printf "  %s\n" "--server, -S SERVER"
-    printf "    Upload to a custom 0x0 instance server\n"
+    printf "    Upload to a custom 0x0 instance server.\n"
     printf "    %s\n" "Default: https://0x0.st/"
     echo
 
@@ -90,7 +101,14 @@ zxz_upload_usage() {
 
     # :argument.usage
     printf "  %s\n" "FILE"
-    printf "    file to upload (max file size: 512MB)\n"
+    printf "    file to upload (max file size: 512MB).\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  zxz upload <filename>\n"
+    printf "  zxz upload <filename> --secret\n"
+    printf "  zxz upload <filename> --server https://<custom-0x0-instance>\n"
     echo
 
   fi
@@ -98,7 +116,7 @@ zxz_upload_usage() {
 
 # :command.usage
 zxz_list_usage() {
-  printf "zxz list - List the files you already uploaded\n\n"
+  printf "zxz list - List the files you already uploaded.\n\n"
   printf "Alias: ls, l\n"
   echo
 
@@ -115,6 +133,16 @@ zxz_list_usage() {
     # :flag.usage
     printf "  %s\n" "--update, -u"
     printf "    Update the list of uploaded files removing the unavailable ones.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--browser, -b"
+    printf "    Pick a file from the list and open in your browser.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--copy-url, -c"
+    printf "    Pick a file from the list and copy URL to clipboard.\n"
     echo
 
     # :command.usage_fixed_flags
@@ -212,6 +240,26 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/custom_commands.sh
+cmd_curl() {
+  cmd_gum_spin \
+    "Sending HTTP request..." \
+    curl --silent --user-agent "$USER_AGENT" \
+    "$@"
+}
+
+cmd_gum_spin() {
+  local message="$1"
+  shift
+  local command=("$@")
+
+  gum spin \
+    --title "$message" \
+    --spinner points \
+    --show-output \
+    -- "${command[@]}"
+}
+
 # src/lib/delete_command.sh
 delete_command() {
   local chosen_url
@@ -227,7 +275,7 @@ delete_command() {
     return 1
   fi
 
-  "${CURL[@]}" \
+  cmd_curl \
     --output /dev/null \
     --form token="$token" \
     --form delete= \
@@ -251,6 +299,9 @@ confirm_url_available() {
     404)
       echo "- <$url>: resource not found in the server (HTTP status ${response_status})." >&2
       ;;
+    '')
+      echo "- <$url>: failed to get the HTTP status." >&2
+      ;;
     *)
       echo "- <$url>: returned HTTP status ${response_status}." >&2
       ;;
@@ -265,25 +316,59 @@ url_http_status() {
   local url="$1"
 
   # getting only the headers and getting the http status code
-  "${CURL[@]}" --head "$url" \
+  cmd_curl --head "$url" \
     | head -1 \
     | cut -d' ' -f2
 }
 
-# src/lib/gum_commands.sh
-gum_spinner() {
-  local message="$1"
-  shift
-  local command=("$@")
+# src/lib/list_command.sh
+list_command() {
+  local url
 
-  gum spin \
-    --title "$message" \
-    --spinner points \
-    --show-output \
-    -- "${command[@]}"
+  if [[ "${ARGS['--copy-url']}" == 1 ]]; then
+    url="$(pick_url_from_log)" \
+      && copy_to_clipboard "$url" \
+      && echo "Copied to clipboard: $url" >&2
+    return
+  fi
+
+  if [[ "${ARGS['--browser']}" == 1 ]]; then
+    url="$(pick_url_from_log)" && open_browser "$url"
+    return
+  fi
+
+  [[ "${ARGS['--update']}" == 1 ]] && update_log_file
+
+  print_uploaded_files
+}
+
+open_browser() {
+  case "$OSTYPE" in
+    darwin*)
+      open "$1"
+      ;;
+    *) # Hopefully Linux
+      xdg-open "$1"
+      ;;
+  esac
+}
+
+copy_to_clipboard() {
+  case "$OSTYPE" in
+    darwin*)
+      echo -n "$1" | pbcopy
+      ;;
+    *) # Hopefully Linux
+      echo -n "$1" | xclip -selection clipboard
+      ;;
+  esac
 }
 
 # src/lib/log_file_operations.sh
+create_log_file() {
+  echo "file;url;token;uploaded_at;expiration_time" > "$ZXZ_LOG_FILE"
+}
+
 log_uploaded_file() {
   local header_file="$1"
   local file="$2"
@@ -297,22 +382,22 @@ log_uploaded_file() {
   local expiration_time
   local date_format="%Y-%m-%d %H:%M:%S %z"
 
-  token="$(get_header_value "$header_file" "X-Token")"
+  token="$(get_http_header_value "$header_file" "X-Token")"
   [[ -z "$token" ]] && echo "[warning] Unable to get the X-Token for this file." >&2
 
-  expiration_ms="$(get_header_value "$header_file" "X-Expires")"
+  expiration_ms="$(get_http_header_value "$header_file" "X-Expires")"
 
   expiration_seconds="$((expiration_ms / 1000))"
   expiration_time="$(date -d "@$expiration_seconds" +"$date_format")"
   uploaded_at="$(date +"$date_format")"
 
-  echo "${file};${url};${token};${uploaded_at};${expiration_time}" >> "$LOG_FILE"
+  echo "${file};${url};${token};${uploaded_at};${expiration_time}" >> "$ZXZ_LOG_FILE"
 }
 
 already_logged() {
   local file="$1"
   local url="$2"
-  grep -qF "${file};${url}" "$LOG_FILE"
+  grep -qF "${file};${url}" "$ZXZ_LOG_FILE"
 }
 
 remove_url_from_log() {
@@ -320,8 +405,8 @@ remove_url_from_log() {
   # shellcheck disable=2155
   local temp_file="$(mktemp)"
 
-  grep -vF ";${url};" "$LOG_FILE" > "$temp_file" \
-    && mv -f "$temp_file" "$LOG_FILE"
+  grep -vF ";${url};" "$ZXZ_LOG_FILE" > "$temp_file" \
+    && mv -f "$temp_file" "$ZXZ_LOG_FILE"
 }
 
 print_uploaded_files() {
@@ -336,7 +421,7 @@ print_uploaded_files() {
 pick_log_line() {
   # CSV format is:
   # filename; url; token; uploaded_at; expiration_time
-  cut -d';' -f1-2,4 "$LOG_FILE" \
+  cut -d';' -f1-2,4 "$ZXZ_LOG_FILE" \
     | gum table \
       --separator=';' \
       --height 10 \
@@ -358,20 +443,26 @@ pick_url_from_log() {
 
 get_url_token_from_log() {
   local url="$1"
-  grep -F ";$url;" "$LOG_FILE" | cut -d';' -f3
+  grep -F ";$url;" "$ZXZ_LOG_FILE" | cut -d';' -f3
 }
 
 update_log_file() {
   local url
 
   while IFS= read -r url; do
+    # TODO: if $url is an empty string, remove the line from the log
+    [[ -z "$url" ]] && warn_corrupted_log_file && continue
     confirm_url_available "$url" \
       || remove_url_from_log "$url"
-  done <<< "$(tail -n +2 "$LOG_FILE" | cut -d';' -f2)"
+  done <<< "$(tail -n +2 "$ZXZ_LOG_FILE" | cut -d';' -f2)"
+}
+
+warn_corrupted_log_file() {
+  echo "[warning] The log file is corrupted (check it at ${ZXZ_LOG_FILE})" >&2
 }
 
 # Get the HTTP header value from the file generated by `curl --dump-header`
-get_header_value() {
+get_http_header_value() {
   local file="$1"
   local header_name="$2"
   local header_value
@@ -388,8 +479,11 @@ get_header_value() {
 
 # src/lib/upload_command.sh
 upload_command() {
-  local file="${ARGS[file]}"
-  local host="${ARGS[--server]}"
+  local file="$1"
+  [[ -z "$file" ]] && return 1
+
+  local host="$2"
+  local upload_as_secret="$3"
   local uploaded_file_url
   # shellcheck disable=2155
   local response_header_file="$(mktemp)"
@@ -398,11 +492,15 @@ upload_command() {
     --form "file=@$file"
   )
 
-  [[ "${ARGS[--secret]}" = 1 ]] && curl_args+=(--form secret=)
+  [[ "$upload_as_secret" == 1 ]] && curl_args+=(--form secret=)
 
-  uploaded_file_url="$("${CURL[@]}" "${curl_args[@]}" "$host")"
+  uploaded_file_url="$(cmd_curl "${curl_args[@]}" "$host")"
+  if [[ -z "$uploaded_file_url" ]]; then
+    echo "Failed to upload file: $file" >&2
+    return 1
+  fi
+
   echo "$uploaded_file_url"
-
   log_uploaded_file "$response_header_file" "$file" "$uploaded_file_url"
   rm -f "$response_header_file"
 }
@@ -423,7 +521,7 @@ validate_http_url() {
 zxz_upload_command() {
 
   # src/upload_command.sh
-  upload_command
+  upload_command "${ARGS[file]}" "${ARGS[--server]}" "${ARGS[--secret]}"
 
 }
 
@@ -431,13 +529,7 @@ zxz_upload_command() {
 zxz_list_command() {
 
   # src/list_command.sh
-  # inspect_args && exit
-
-  if [[ "${ARGS[--update]}" == 1 ]]; then
-    update_log_file
-  fi
-
-  print_uploaded_files
+  list_command
 
 }
 
@@ -472,6 +564,12 @@ parse_requirements() {
 
     esac
   done
+
+  # :command.environment_variables_filter
+  # :command.environment_variables_default
+  export ZXZ_LOG_FILE="${ZXZ_LOG_FILE:-${LOG_DIR}/uploads.log}"
+
+  env_var_names+=("ZXZ_LOG_FILE")
 
   # :command.dependencies_filter
   missing_deps=
@@ -524,7 +622,7 @@ parse_requirements() {
 
   case $action in
 
-    upload)
+    upload | up | u)
       action="upload"
       shift
       zxz_upload_parse_requirements "$@"
@@ -711,6 +809,22 @@ zxz_list_parse_requirements() {
         shift
         ;;
 
+      # :flag.case
+      --browser | -b)
+
+        # :flag.case_no_arg
+        args['--browser']=1
+        shift
+        ;;
+
+      # :flag.case
+      --copy-url | -c)
+
+        # :flag.case_no_arg
+        args['--copy-url']=1
+        shift
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -787,8 +901,8 @@ initialize() {
   # :variable.definition
   declare -g LOG_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/zxz"
 
-  # :variable.definition
-  declare -g LOG_FILE="${LOG_DIR}/uploads.log"
+  # :command.environment_variables_default
+  export ZXZ_LOG_FILE="${ZXZ_LOG_FILE:-${LOG_DIR}/uploads.log}"
 
   # :command.globals
   declare -g -A args=()
@@ -799,12 +913,12 @@ initialize() {
   declare -gn ARGS=args
 
   # src/initialize.sh
-  mkdir -p "$LOG_DIR"
+  [[ -d "$LOG_DIR" ]] || mkdir -p "$LOG_DIR"
 
-  export CURL=(
-    gum_spinner "Sending HTTP request..."
-    curl --silent --user-agent "$USER_AGENT"
-  )
+  # if file does not exists or is empty, create it.
+  if [[ ! -s "$ZXZ_LOG_FILE" ]]; then
+    create_log_file
+  fi
 
 }
 
@@ -820,5 +934,7 @@ run() {
   esac
 }
 
-initialize
-run "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  initialize
+  run "$@"
+fi
