feat: add help subcommand

diff --git a/zxz b/zxz
--- a/zxz
+++ b/zxz
@@ -2,20 +2,15 @@
 # This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
-# :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
   printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
-# :command.master_script
-
-# :command.version_command
 version_command() {
   echo "$version"
 }
 
-# :command.usage
 zxz_usage() {
   printf "zxz - a CLI to interact with <https://0x0.st/>.\n\n"
 
@@ -24,18 +19,17 @@ zxz_usage() {
   printf "  zxz [COMMAND] --help | -h\n"
   printf "  zxz --version | -v\n"
   echo
-  # :command.usage_commands
+
   printf "%s\n" "Commands:"
+  printf "  %s   Show help about a command\n" "help  "
   printf "  %s   Upload FILE. (default)\n" "upload"
   printf "  %s   List the files you already uploaded.\n" "list  "
   printf "  %s   Delete an uploaded file from the remote server.\n" "delete"
   echo
 
-  # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -43,28 +37,47 @@ zxz_usage() {
     printf "    Show version number\n"
     echo
 
-    # :command.usage_environment_variables
     printf "%s\n" "Environment Variables:"
 
-    # :environment_variable.usage
     printf "  %s\n" "ZXZ_LOG_FILE"
     printf "    Path to the log file.\n"
     printf "    %s\n" "Default: ${LOG_DIR}/uploads.log"
     echo
 
-    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  The most simple usage is when you just want to upload a file:\n  $ zxz <filename>\n"
     echo
 
-    # :command.footer
     printf "Credits:\n  zxz repository: <https://github.com/meleu/zxz>\n\n  The <https://0x0.st/> is a service maintained by Mia Herkt,\n  consider supporting them financially (check the webpage).\n\n"
     echo
 
   fi
 }
 
-# :command.usage
+zxz_help_usage() {
+  printf "zxz help - Show help about a command\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  zxz help [COMMAND]\n"
+  printf "  zxz help --help | -h\n"
+  echo
+
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    printf "%s\n" "Arguments:"
+
+    printf "  %s\n" "COMMAND"
+    printf "    Help subject\n"
+    echo
+
+  fi
+}
+
 zxz_upload_usage() {
   printf "zxz upload - Upload FILE.\n\n"
   printf "Alias: up, u\n"
@@ -75,46 +88,36 @@ zxz_upload_usage() {
   printf "  zxz upload --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_flags
-    # :flag.usage
     printf "  %s\n" "--secret, -s"
     printf "    Ask the server to generate a longer and hard-to-guess URL.\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--server, -S SERVER"
     printf "    Upload to a custom 0x0 instance server.\n"
     printf "    %s\n" "Default: https://0x0.st/"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--copy-url, -c"
     printf "    After successfully uploading the file, copy the URL to clipboard.\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--retention-hours, -r RETENTION_HOURS"
     printf "    Set the amount of hours you want the file to be available.\n"
     echo
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
-    # :command.usage_args
     printf "%s\n" "Arguments:"
 
-    # :argument.usage
     printf "  %s\n" "FILE"
     printf "    file to upload (max file size: 512MB).\n"
     echo
 
-    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  zxz upload <filename>\n"
     printf "  zxz upload <filename> --secret\n"
@@ -124,7 +127,6 @@ zxz_upload_usage() {
   fi
 }
 
-# :command.usage
 zxz_list_usage() {
   printf "zxz list - List the files you already uploaded.\n\n"
   printf "Alias: ls, l\n"
@@ -135,27 +137,21 @@ zxz_list_usage() {
   printf "  zxz list --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_flags
-    # :flag.usage
     printf "  %s\n" "--update, -u"
     printf "    Update the list of uploaded files removing the unavailable ones.\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--browser, -b"
     printf "    Pick a file from the list and open in your browser.\n"
     echo
 
-    # :flag.usage
     printf "  %s\n" "--copy-url, -c"
     printf "    Pick a file from the list and copy URL to clipboard.\n"
     echo
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -163,7 +159,6 @@ zxz_list_usage() {
   fi
 }
 
-# :command.usage
 zxz_delete_usage() {
   printf "zxz delete - Delete an uploaded file from the remote server.\n\n"
   printf "Alias: del, d\n"
@@ -174,11 +169,9 @@ zxz_delete_usage() {
   printf "  zxz delete --help | -h\n"
   echo
 
-  # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -186,8 +179,6 @@ zxz_delete_usage() {
   fi
 }
 
-# :command.normalize_input
-# :command.normalize_input_function
 normalize_input() {
   local arg passthru flags
   passthru=false
@@ -218,39 +209,6 @@ normalize_input() {
   done
 }
 
-# :command.inspect_args
-inspect_args() {
-  if ((${#args[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
-    echo args:
-    for k in "${sorted_keys[@]}"; do
-      echo "- \${args[$k]} = ${args[$k]}"
-    done
-  else
-    echo args: none
-  fi
-
-  if ((${#deps[@]})); then
-    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
-    echo
-    echo deps:
-    for k in "${sorted_keys[@]}"; do
-      echo "- \${deps[$k]} = ${deps[$k]}"
-    done
-  fi
-
-  if ((${#env_var_names[@]})); then
-    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
-    echo
-    echo "environment variables:"
-    for k in "${sorted_names[@]}"; do
-      echo "- \$$k = ${!k:-}"
-    done
-  fi
-}
-
-# :command.user_lib
-# src/lib/custom_commands.sh
 cmd_curl() {
   cmd_gum_spin \
     "Sending HTTP request..." \
@@ -270,7 +228,6 @@ cmd_gum_spin() {
     -- "${command[@]}"
 }
 
-# src/lib/delete_functions.sh
 delete_command() {
   local chosen_url
   local token
@@ -331,7 +288,6 @@ url_http_status() {
     | cut -d' ' -f2
 }
 
-# src/lib/list_functions.sh
 pick_and_copy_url() {
   local url
   url="$(pick_url_from_log)" \
@@ -366,7 +322,6 @@ copy_to_clipboard() {
   esac
 }
 
-# src/lib/log_file_operations.sh
 create_log_file() {
   echo "file;url;token;uploaded_at;expiration_time" > "$ZXZ_LOG_FILE"
 }
@@ -480,7 +435,6 @@ get_http_header_value() {
   echo "$header_value"
 }
 
-# src/lib/upload_functions.sh
 upload_command() {
   [[ -z "$1" ]] && return 1
 
@@ -513,35 +467,50 @@ upload_command() {
   rm -f "$response_header_file"
 }
 
-# src/lib/validations/validate_file_exists.sh
 validate_file_exists() {
   [[ -f "$1" ]] || echo "must be an existing file"
 }
 
-# src/lib/validations/validate_http_url.sh
 validate_http_url() {
   local regex_http_url="^https?://[^[:space:]/$.?#].[^[:space:]]*$"
   [[ $1 =~ $regex_http_url ]] || echo "must be a valid http URL"
 }
 
-# src/lib/validations/validate_integer.sh
 validate_integer() {
   [[ "$1" =~ ^[0-9]+$ ]] || echo "must be an integer"
 }
 
-# :command.command_functions
-# :command.function
+zxz_help_command() {
+
+  command="${args[command]:-}"
+  long_usage=yes
+
+  if [[ -z "$command" ]]; then
+    # No command argument, show the global help
+    help_function=zxz_usage
+  else
+    # Show the help for the requested command
+    help_function="zxz_${command}_usage"
+  fi
+
+  # Call the help function if it exists
+  if [[ $(type -t "$help_function") ]]; then
+    "$help_function"
+  else
+    echo "No help available for this command"
+    exit 1
+  fi
+
+}
+
 zxz_upload_command() {
 
-  # src/upload_command.sh
   upload_command "${ARGS[file]}" "${ARGS[--server]}"
 
 }
 
-# :command.function
 zxz_list_command() {
 
-  # src/list_command.sh
   if [[ "${ARGS['--copy-url']}" == 1 ]]; then
     pick_and_copy_url
     return
@@ -558,17 +527,14 @@ zxz_list_command() {
 
 }
 
-# :command.function
 zxz_delete_command() {
 
-  # src/delete_command.sh
   delete_command
 
 }
 
-# :command.parse_requirements
 parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -590,15 +556,12 @@ parse_requirements() {
     esac
   done
 
-  # :command.environment_variables_filter
-  # :command.environment_variables_default
   export ZXZ_LOG_FILE="${ZXZ_LOG_FILE:-${LOG_DIR}/uploads.log}"
 
   env_var_names+=("ZXZ_LOG_FILE")
 
-  # :command.dependencies_filter
   missing_deps=
-  # :dependency.filter
+
   if ! command -v curl >/dev/null 2>&1; then
     printf "missing dependency: curl\n" >&2
     missing_deps=1
@@ -606,7 +569,6 @@ parse_requirements() {
     deps['curl']="$(command -v curl | head -n1)"
   fi
 
-  # :dependency.filter
   if ! command -v gum >/dev/null 2>&1; then
     printf "missing dependency: gum\n" >&2
     missing_deps=1
@@ -614,7 +576,6 @@ parse_requirements() {
     deps['gum']="$(command -v gum | head -n1)"
   fi
 
-  # :dependency.filter
   if ! command -v cut >/dev/null 2>&1; then
     printf "missing dependency: cut\n" >&2
     missing_deps=1
@@ -622,7 +583,6 @@ parse_requirements() {
     deps['cut']="$(command -v cut | head -n1)"
   fi
 
-  # :dependency.filter
   if ! command -v date >/dev/null 2>&1; then
     printf "missing dependency: date\n" >&2
     missing_deps=1
@@ -630,7 +590,6 @@ parse_requirements() {
     deps['date']="$(command -v date | head -n1)"
   fi
 
-  # :dependency.filter
   if ! command -v grep >/dev/null 2>&1; then
     printf "missing dependency: grep\n" >&2
     missing_deps=1
@@ -642,10 +601,16 @@ parse_requirements() {
     exit 1
   fi
 
-  # :command.command_filter
   action=${1:-}
 
   case $action in
+
+    help)
+      action="help"
+      shift
+      zxz_help_parse_requirements "$@"
+      shift $#
+      ;;
 
     upload | up | u)
       action="upload"
@@ -668,7 +633,6 @@ parse_requirements() {
       shift $#
       ;;
 
-    # :command.command_fallback
     "")
       zxz_usage >&2
       exit 1
@@ -682,7 +646,6 @@ parse_requirements() {
 
   esac
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -693,8 +656,7 @@ parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -705,9 +667,54 @@ parse_requirements() {
 
 }
 
-# :command.parse_requirements
+zxz_help_parse_requirements() {
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        zxz_help_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  action="help"
+
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+
+        if [[ -z ${args['command']+x} ]]; then
+          args['command']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
 zxz_upload_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -724,25 +731,20 @@ zxz_upload_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="upload"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
+
       --secret | -s)
 
-        # :flag.case_no_arg
         args['--secret']=1
         shift
         ;;
 
-      # :flag.case
       --server | -S)
 
-        # :flag.case_arg
         if [[ -n ${2+x} ]]; then
           args['--server']="$2"
           shift
@@ -753,18 +755,14 @@ zxz_upload_parse_requirements() {
         fi
         ;;
 
-      # :flag.case
       --copy-url | -c)
 
-        # :flag.case_no_arg
         args['--copy-url']=1
         shift
         ;;
 
-      # :flag.case
       --retention-hours | -r)
 
-        # :flag.case_arg
         if [[ -n ${2+x} ]]; then
           args['--retention-hours']="$2"
           shift
@@ -781,9 +779,7 @@ zxz_upload_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        # :argument.case
+
         if [[ -z ${args['file']+x} ]]; then
           args['file']=$1
           shift
@@ -797,30 +793,24 @@ zxz_upload_parse_requirements() {
     esac
   done
 
-  # :command.required_args_filter
   if [[ -z ${args['file']+x} ]]; then
     printf "missing required argument: FILE\nusage: zxz [upload] FILE [OPTIONS]\n" >&2
 
     exit 1
   fi
 
-  # :command.default_assignments
   [[ -n ${args['--server']:-} ]] || args['--server']="https://0x0.st/"
 
-  # :command.validations
-  # :argument.validations
   if [[ -v args['file'] && -n $(validate_file_exists "${args['file']:-}") ]]; then
     printf "validation error in %s:\n%s\n" "FILE" "$(validate_file_exists "${args['file']:-}")" >&2
     exit 1
   fi
 
-  # :flag.validations
   if [[ -v args['--server'] && -n $(validate_http_url "${args['--server']:-}") ]]; then
     printf "validation error in %s:\n%s\n" "--server, -S SERVER" "$(validate_http_url "${args['--server']:-}")" >&2
     exit 1
   fi
 
-  # :flag.validations
   if [[ -v args['--retention-hours'] && -n $(validate_integer "${args['--retention-hours']:-}") ]]; then
     printf "validation error in %s:\n%s\n" "--retention-hours, -r RETENTION_HOURS" "$(validate_integer "${args['--retention-hours']:-}")" >&2
     exit 1
@@ -828,9 +818,8 @@ zxz_upload_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 zxz_list_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -847,33 +836,26 @@ zxz_list_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="list"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-      # :flag.case
+
       --update | -u)
 
-        # :flag.case_no_arg
         args['--update']=1
         shift
         ;;
 
-      # :flag.case
       --browser | -b)
 
-        # :flag.case_no_arg
         args['--browser']=1
         shift
         ;;
 
-      # :flag.case
       --copy-url | -c)
 
-        # :flag.case_no_arg
         args['--copy-url']=1
         shift
         ;;
@@ -884,8 +866,7 @@ zxz_list_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -896,9 +877,8 @@ zxz_list_parse_requirements() {
 
 }
 
-# :command.parse_requirements
 zxz_delete_parse_requirements() {
-  # :command.fixed_flags_filter
+
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -915,10 +895,8 @@ zxz_delete_parse_requirements() {
     esac
   done
 
-  # :command.command_filter
   action="delete"
 
-  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -929,8 +907,7 @@ zxz_delete_parse_requirements() {
         ;;
 
       *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
+
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -941,23 +918,17 @@ zxz_delete_parse_requirements() {
 
 }
 
-# :command.initialize
 initialize() {
   version="0.1.2"
   long_usage=''
   set -Eeo pipefail
 
-  # :command.variables
-  # :variable.definition
   declare -g USER_AGENT="zxz/$version - https://github.com/meleu/zxz"
 
-  # :variable.definition
   declare -g LOG_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/zxz"
 
-  # :command.environment_variables_default
   export ZXZ_LOG_FILE="${ZXZ_LOG_FILE:-${LOG_DIR}/uploads.log}"
 
-  # :command.globals
   declare -g -A args=()
   declare -g -A deps=()
   declare -g -a env_var_names=()
@@ -965,7 +936,6 @@ initialize() {
 
   declare -gn ARGS=args
 
-  # src/initialize.sh
   [[ -d "$LOG_DIR" ]] || mkdir -p "$LOG_DIR"
 
   # if file does not exists or is empty, create it.
@@ -975,19 +945,17 @@ initialize() {
 
 }
 
-# :command.run
 run() {
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "help") zxz_help_command ;;
     "upload") zxz_upload_command ;;
     "list") zxz_list_command ;;
     "delete") zxz_delete_command ;;
   esac
 }
 
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-  initialize
-  run "$@"
-fi
+initialize
+run "$@"
