feat: 'list --update' to check URL availability

diff --git a/zxz b/zxz
--- a/zxz
+++ b/zxz
@@ -99,13 +99,19 @@ zxz_list_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  zxz list\n"
+  printf "  zxz list [OPTIONS]\n"
   printf "  zxz list --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--update, -u"
+    printf "    Update the list of uploaded files removing the unavailable ones.\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -223,26 +229,26 @@ delete_command() {
     --form delete= \
     "$chosen_url"
 
-  confirm_url_not_available "$chosen_url"
-  remove_url_from_log "$chosen_url"
+  confirm_url_available "$chosen_url" \
+    || remove_url_from_log "$chosen_url"
 }
 
-confirm_url_not_available() {
+confirm_url_available() {
   local url="$1"
   local response_status
 
   response_status="$(url_http_status "$url")"
 
   case "$response_status" in
-    404)
-      echo "[success] The file was successfully deleted from server."
+    200)
+      echo "- <$url>: is still available." >&2
       return 0
       ;;
-    200)
-      echo "[fail] The URL is still available."
+    404)
+      echo "- <$url>: resource not found in the server (HTTP status ${response_status})." >&2
       ;;
     *)
-      echo "[fail] Unable to confirm the deletion (returned HTTP status ${response_status})."
+      echo "- <$url>: returned HTTP status ${response_status}." >&2
       ;;
   esac
 
@@ -351,6 +357,16 @@ get_url_token_from_log() {
   grep -F ";$url;" "$LOG_FILE" | cut -d';' -f3
 }
 
+update_log_file() {
+  local url
+
+  while IFS= read -r url; do
+    confirm_url_available "$url" \
+      || remove_url_from_log "$url"
+  done <<< "$(tail -n +2 "$LOG_FILE" | cut -d';' -f2)"
+}
+
+# Get the HTTP header value from the file generated by `curl --dump-header`
 get_header_value() {
   local file="$1"
   local header_name="$2"
@@ -403,8 +419,6 @@ validate_http_url() {
 zxz_upload_command() {
 
   # src/upload_command.sh
-  # inspect_args && exit
-
   upload_command
 
 }
@@ -413,6 +427,12 @@ zxz_upload_command() {
 zxz_list_command() {
 
   # src/list_command.sh
+  # inspect_args && exit
+
+  if [[ "${ARGS[--update]}" == 1 ]]; then
+    update_log_file
+  fi
+
   print_uploaded_files
 
 }
@@ -663,6 +683,13 @@ zxz_list_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --update | -u)
+
+        # :flag.case_no_arg
+        args['--update']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
